//Hasan Pekedis 150120068
//This class's object represents an item generated by the employees working for the factory.
//startShift method assigns unique id for each item and then adds in items. Finally it returns items. 
//endShift method create payroll objects for Payroll class. It returns payroll object. 
//toString method returns a string text that contain information about the employee.
//There are set and get methods for each data field.
public class Employee {
    private int id;
    private String name;
    private String surname;
    private int workHour;
    private int speed;
    private Item[] items;
    private Payroll payroll;

    public Employee(int id, String name, String surname, int workHour, int speed){
        this.id = id;
        this.name = name;
        this.surname = surname;
        this.workHour = workHour;
        this.speed = speed;
    }
    
    public Item[] startShift(){
        int shouldProduce = speed * workHour;
        Item[] items = new Item[shouldProduce];
        for (int i = 0; i < shouldProduce; i++){
            items[i] = new Item((int) (Math.random() * 100));
        }
        this.items = items;
        return items;
    }
    
    public Payroll endShift(){
        Payroll payroll = new Payroll(workHour, items.length);
        this.payroll = payroll;
        return payroll;
    }
    
    public String toString(){
        String a = "This is the employee with id " 
        + id + " speed " + speed + ". The work hour is " 
        + workHour + " and the produced item count is " + items.length + ".";
        return a;
    }
    
    public int getId() {
        return id;
    }
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return name;
    }
    public void setName(String name) {
        this.name = name;
    }
    public String getSurname() {
        return surname;
    }
    public void setSurname(String surname) {
        this.surname = surname;
    }
    public int getWorkHour() {
        return workHour;
    }
    public void setWorkHour(int workHour) {
        this.workHour = workHour;
    }
    public int getSpeed() {
        return speed;
    }
    public void setSpeed(int speed) {
        this.speed = speed;
    }
    public Item[] getItems() {
        return items;
    }
    public void setItems(Item[] items) {
        this.items = items;
    }
    public Payroll getPayroll() {
        return payroll;
    }
    public void setPayroll(Payroll payroll) {
        this.payroll = payroll;
    }
    

}