//Hasan Pekedis 150120068
//This class's object represents an item generated by the employees working for the factory.
//There are only set and get methods in this class(except constructor method). 
//There are no extra methods.
public class Item {

	private int id;
    public static int numberOfItems;

    public Item(int id){
        this.id = id;
        numberOfItems = numberOfItems + 1;
    }
    public int getId() {
        return id;
    }
    public void setId(int id) {
        this.id = id;
    }
    public int getNumberOfItems() {
        return numberOfItems;
    }
    public void setNumberOfItems(int numberOfItems) {
        Item.numberOfItems = numberOfItems;
    }

    

  
    
    
}